### ISSUE TITLE
view_001.png does not show the lateral view when exporting a patient

### ISSUE THREAD

**Issue by jAchtzehn** [netstim/leaddbs#486]
### Summary
When exporting a reconstructed patient, view_001.png does not show the lateral view, but instead a screenshot of the view control figure.

### Actual behavior
When exporting, several figures are created to take appropriate screenshots of the 3D renderer. view_001.png is showing a screenshot instead of the lateral view. 

### Expected behavior
When exporting, several figures are created to take appropriate screenshots of the 3D renderer. view_001.png should show a lateral view of the electrode.

### How to replicate the behavior
On the main GUI: Tools -> Export -> Export .zip for selected patient...

### Platform details: 
Ubuntu 20.04 LTS
Matlab R2020b Update 2
lead dbs commit #485 (9f5b18a30f2f0b49dae1c6008659bdd67dea3713)

**Comment by jAchtzehn** [comment]
@ningfei would you be so kind to check if this problem is present on a different operating system as well? I would see to the fix myself.

**Comment by andreashorn** [comment]
Hi Johannes,
the problem is probably only if you click to other figures. If you take hands off from the mouse it should export everything correctly. We had added in the function when the only person doing it was myself so it was fine :) (uploading things to the movebase back then).
But it's surely something that could / should be fixed (likely involves some gcf command instead of a proper pointer to the resultfig). Would be great if you can fix it. Is not OS dependent.

**Comment by jAchtzehn** [comment]
Thanks for the feedback. I was already suspecting it had to do with gcf selecting the wrong figure. Interestingly enough, on my Ubuntu system, even if I do not select any other figure, the view still does not get exported correctly.
Should be an easy fix, I will take a look at it.

**Comment by ningfei** [comment]
Thanks for the report! As Andy suggested, maybe better to use the resultfig handle explicitly.
